sudo: required
dist: trusty

language: cpp

os:
- linux
- osx
- windows

branches:
  only:
    - master

# Use a Travis image containing an Xcode we support
# This prevents surprise upgrades!
osx_image: xcode7.3

# Environment variables
env:
  global:
   - CXX_STD: "c++11"

jdk:
  - openjdk8

# Install any required tools
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      sudo apt-get -qq update
      sudo apt-get -qq install g++-4.9
    fi

script: |
  echo "Building mergMarkdown"
  case "${TRAVIS_OS_NAME}" in
    linux)
      BUILD_PLATFORM=linux
      CHECK_COMMAND=xvfb-run
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"${JAVA_HOME}/jre/lib/amd64/server"
      export CXX="g++-4.9"
      export CC="gcc-4.9"
      make mergMarkdown-x64.so
    ;;
    osx)
      BUILD_PLATFORM=mac
      CHECK_COMMAND=
      export XCODE_TARGET_SDK=macosx10.11
      export XCODEBUILD="set -o pipefail && xcodebuild"
      export JAVA_HOME=$(/usr/libexec/java_home)
      xcodebuild -project mergMarkdown.xcodeproj -configuration Debug -target mergMarkdown-OSX -UseModernBuildSystem=NO build
    ;;
    windows)
      export MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      export PATH=$MSBUILD_PATH:$PATH
      MSBuild.exe "mergMarkdown\mergMarkdown.sln" //fl //flp:Verbosity=normal //nologo //m:1 //p:Configuration=Debug //p:Platform=x64
    ;;
  esac
  if [ $? -ne 0 ] ; then
    echo "    compile failed"
    exit 1
  fi

  # Run tests on mac and linux
  if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]] ; then
    echo "Building LiveCode"
    export MODE=debug
    git clone --depth 1 --recursive https://github.com/livecode/livecode.git &&
    cd livecode/prebuilt && 
    ./fetch-libraries.sh linux &&
    cd .. &&
    make all-${BUILD_PLATFORM}
    if [ $? -ne 0 ] ; then
        echo "    compile failed"
        exit 1
    fi

    cd ..

    echo "Running Tests"
    ${CHECK_COMMAND} make -C tests lcs-check
    if [ $? -ne 0 ] ; then
        echo "    tests failed - dumping log file"
        cat tests/_lcs_test_suite.log
        exit 1
    fi
  fi

addons:
  # Packages needed for building LiveCode
  apt:
    packages:
      - gawk
      - libx11-dev
      - libxext-dev
      - libxrender-dev
      - libxft-dev
      - libxinerama-dev
      - libxv-dev
      - libxcursor-dev
      - libfreetype6-dev
      - libgtk2.0-dev
      - libpopt-dev
      - libesd0-dev
      - liblcms2-dev
      - xvfb

# before_script: mkdir binaries
# script: make mergMarkdown-x64.so
# deploy:
#   provider: releases
#   api_key:
#     secure: 7rskNJLV3xIjGbucGZAJzBnm6pBYfNy1FLQQ9l+nF8AShC37pjfQB3/djQIE2A6kkVsI0s+guio3gy6lWd7HNa259K3Vw6MZGvYA8DVE/XeYCUa/8CllRfWTt9FgzBC3NeVzZyC0pGTD8lpVDqPLSRb9Ljml92SYDUQD8dmwyC3UTBZRMIecF6jniIijcFtJjJDZeFNM6EqYSJwmdEVEp1BQjLsjGGunsxljJ8lB40eKp9HVmNReqaYY/OTKMq2FbA27G7GbEtLoCBP1rzVL9mCeOYnJaL+KmcxyFLkoXlxaIq/N+azSh4Te1wqZWuBw8s7reZAby6YqKzQAOPhc5sMnvkZwESoEpF+ddheTAYxRcryLy5IkrFlFXYeYuQJIesAtU10x57Iilb9wxH3yVPI18QJMb37QWlRRjmRmqtRaFar3C6OviIC1KL/MT44PqdufjSLlhTdU1rq0GM9o3Lq7TQK09uyb0saTsSwCU5tgBski5h+Yr/MDj8H+9TfLv25OIhANSGc0i+TvdfaLCFrLjMLTD7eqXWF7pF1JqWBm43hyOrvhFWOIPdv0HtVECoc5XfJmmVHplQ/xiiLzSaTQoK3zc+W7gL6rrlS6taCwSO8u/Jf5I6PUYWuNUKyjxvHRC7kImy2d25rUgKt2vSZm1mjtTzngzgFUYHyNpT4=
#   file: binaries/mergMarkdown-x64.so
#   on:
#     repo: montegoulding/mergMarkdown
#     tags: true
